@CargoFlow_Api_HostAddress = http://localhost:5266

### Get shipments

GET {{CargoFlow_Api_HostAddress}}/api/shipments
Accept: application/json

###

### Get shipment by ID

GET {{CargoFlow_Api_HostAddress}}/api/shipments/1
Accept: application/json

###

### Get shipment that does not exist

GET {{CargoFlow_Api_HostAddress}}/api/shipments/999999
Accept: application/json

###

### Create shipment

POST {{CargoFlow_Api_HostAddress}}/api/shipments
Content-Type: application/json

{
  "customerId": 1,
  "originCity": "Cologne",
  "destinationCity": "Berlin",
  "weight": 850.5
}

###

### Create shipment with nonexistent customer

POST {{CargoFlow_Api_HostAddress}}/api/shipments
Content-Type: application/json

{
  "customerId": 999999,
  "originCity": "Cologne",
  "destinationCity": "Berlin",
  "weight": 850.5
}

###

### Create shipment with invalid weight

POST {{CargoFlow_Api_HostAddress}}/api/shipments
Content-Type: application/json

{
  "customerId": 1,
  "originCity": "Cologne",
  "destinationCity": "Berlin",
  "weight": 0
}

###

### Get customers

GET {{CargoFlow_Api_HostAddress}}/api/customers
Accept: application/json

###

### Create customer

POST {{CargoFlow_Api_HostAddress}}/api/customers
Content-Type: application/json

{
  "name": "API Test Customer"
}

###

### Get customer by ID

GET {{CargoFlow_Api_HostAddress}}/api/customers/1
Accept: application/json

###

### Get customer that does not exist

GET {{CargoFlow_Api_HostAddress}}/api/customers/999999
Accept: application/json

###